import { Customer } from '../types/customer';
 
export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: '1',
    name: 'Somsak Jaidee',
    email: 'somsak.j@example.com',
    status: 'active',
    phone: '081-234-5678',
    company: 'Acme Corp',
    address: '123 Sukhumvit Rd, Bangkok',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Malee Srisuk',
    email: 'malee.s@example.com',
    status: 'inactive',
    phone: '089-876-5432',
    company: 'Beta Solutions',
    address: '456 Silom Rd, Bangkok',
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    name: 'Nattapong Buathong',
    email: 'nattapong.b@example.com',
    status: 'active',
    phone: '062-111-2222',
    company: 'Gamma Tech',
    address: '789 Rama 9, Bangkok',
    createdAt: '2024-03-10',
  },
  {
    id: '4',
    name: 'Pimchanok Rattana',
    email: 'pimchanok.r@example.com',
    status: 'active',
    phone: '091-333-4444',
    company: 'Delta Inc',
    address: '321 Lad Prao, Bangkok',
    createdAt: '2024-04-05',
  },
  {
    id: '5',
    name: 'Wichai Promma',
    email: 'wichai.p@example.com',
    status: 'inactive',
    phone: '083-555-6666',
    company: 'Epsilon Ltd',
    address: '654 Charoennakorn, Bangkok',
    createdAt: '2024-05-18',
  },
  {
    id: '6',
    name: 'Sunisa Charoenwong',
    email: 'sunisa.c@example.com',
    status: 'active',
    phone: '095-777-8888',
    company: 'Zeta Group',
    address: '987 On Nut, Bangkok',
    createdAt: '2024-06-22',
  },
  {
    id: '7',
    name: 'Anuwat Sombat',
    email: 'anuwat.s@example.com',
    status: 'active',
    phone: '086-999-0000',
    company: 'Eta Services',
    address: '147 Sathorn, Bangkok',
    createdAt: '2024-07-30',
  },
  {
    id: '8',
    name: 'Kanchana Phromma',
    email: 'kanchana.p@example.com',
    status: 'inactive',
    phone: '088-123-9999',
    company: 'Theta Corp',
    address: '258 Ratchada, Bangkok',
    createdAt: '2024-08-14',
  },
];